version: '3.2'
services:
  db:
    container_name: database
    image: postgres:9.6
    ports:
    - 5432:5432
    networks:
      development:
    volumes:
    - database:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "dev"
      POSTGRES_USER: "dev"
      POSTGRES_PASSWORD: "dev"

  web:
    container_name: webserver
    image: dhbw_php:2020
    ports:
    - 8080:80
    networks:
      development:
    depends_on:
      - db
    volumes:
    - type: bind
      source: "./src"
      target: "/var/www/html/"
    - webserver:/data

volumes:
  database:
  webserver:

networks:
  development:
    driver: bridge
